# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: test.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ntest.proto\"H\n\x05Graph\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\x17\n\x06inputs\x18\x02 \x03(\x0b\x32\x07.Tensor\x12\x18\n\x07outputs\x18\x03 \x03(\x0b\x32\x07.Tensor\"2\n\x04\x44ims\x12\t\n\x01N\x18\x01 \x02(\x05\x12\t\n\x01H\x18\x02 \x02(\x05\x12\t\n\x01W\x18\x03 \x02(\x05\x12\t\n\x01\x43\x18\x04 \x02(\x05\"<\n\x06Tensor\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\x13\n\x04\x64ims\x18\x03 \x02(\x0b\x32\x05.Dims\x12\x0f\n\x07value_f\x18\x02 \x03(\x02')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'test_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GRAPH._serialized_start=14
  _GRAPH._serialized_end=86
  _DIMS._serialized_start=88
  _DIMS._serialized_end=138
  _TENSOR._serialized_start=140
  _TENSOR._serialized_end=200
# @@protoc_insertion_point(module_scope)
